"""Offline geolocation for demo hops. Optional live lookup is layered on top.

These coordinates are public anycast / well-known infrastructure ranges used
only so the map works with no API key and no MaxMind download.
"""

from __future__ import annotations

GEO_BY_IP: dict[str, dict] = {
    "8.8.8.8": {
        "city": "Mountain View",
        "region": "California",
        "country": "United States",
        "lat": 37.4056,
        "lon": -122.0775,
        "isp": "Google LLC",
        "org": "Google Public DNS",
        "threat_tag": "public_resolver",
    },
    "1.1.1.1": {
        "city": "Los Angeles",
        "region": "California",
        "country": "United States",
        "lat": 34.0522,
        "lon": -118.2437,
        "isp": "Cloudflare",
        "org": "Cloudflare DNS",
        "threat_tag": "cdn",
    },
    "103.21.244.17": {
        "city": "Mumbai",
        "region": "Maharashtra",
        "country": "India",
        "lat": 19.0760,
        "lon": 72.8777,
        "isp": "Cloudflare India PoP",
        "org": "Cloudflare",
        "threat_tag": "cdn",
    },
    "49.207.50.12": {
        "city": "Bengaluru",
        "region": "Karnataka",
        "country": "India",
        "lat": 12.9716,
        "lon": 77.5946,
        "isp": "Airtel Broadband",
        "org": "Bharti Airtel",
        "threat_tag": "consumer_isp",
    },
    "117.239.80.44": {
        "city": "Delhi",
        "region": "Delhi",
        "country": "India",
        "lat": 28.6139,
        "lon": 77.2090,
        "isp": "NKN / Academic",
        "org": "National Knowledge Network",
        "threat_tag": "edu",
    },
    "52.95.110.1": {
        "city": "Boardman",
        "region": "Oregon",
        "country": "United States",
        "lat": 45.8234,
        "lon": -119.7257,
        "isp": "Amazon.com",
        "org": "AWS",
        "threat_tag": "cloud",
    },
    "185.220.101.47": {
        "city": "unknown",
        "region": "",
        "country": "Germany",
        "lat": 50.1109,
        "lon": 8.6821,
        "isp": "CIA TRIAD SECURITY LLC",
        "org": "Tor exit (demo tag)",
        "threat_tag": "anonymizer",
    },
    "45.77.88.21": {
        "city": "Singapore",
        "region": "Singapore",
        "country": "Singapore",
        "lat": 1.3521,
        "lon": 103.8198,
        "isp": "The Constant Company",
        "org": "Vultr",
        "threat_tag": "vps",
    },
    "91.219.237.12": {
        "city": "Amsterdam",
        "region": "North Holland",
        "country": "Netherlands",
        "lat": 52.3676,
        "lon": 4.9041,
        "isp": "Bulletproof VPS (demo)",
        "org": "Hosting",
        "threat_tag": "bulletproof_host",
    },
    "142.250.190.14": {
        "city": "Council Bluffs",
        "region": "Iowa",
        "country": "United States",
        "lat": 41.2619,
        "lon": -95.8608,
        "isp": "Google",
        "org": "Gmail MX",
        "threat_tag": "mailbox_provider",
    },
    "40.92.0.12": {
        "city": "Washington",
        "region": "D.C.",
        "country": "United States",
        "lat": 38.9072,
        "lon": -77.0369,
        "isp": "Microsoft",
        "org": "Outlook.com",
        "threat_tag": "mailbox_provider",
    },
    "202.141.80.10": {
        "city": "Guwahati",
        "region": "Assam",
        "country": "India",
        "lat": 26.1445,
        "lon": 91.7362,
        "isp": "NIXI / Academic",
        "org": "Campus MX (demo)",
        "threat_tag": "edu",
    },
}

PREFIX_FALLBACK = [
    ("185.220.", GEO_BY_IP["185.220.101.47"]),
    ("52.", GEO_BY_IP["52.95.110.1"]),
    ("49.207.", GEO_BY_IP["49.207.50.12"]),
    ("117.", GEO_BY_IP["117.239.80.44"]),
]
