"""Final feasibility slide diagrams — max readable type, DevWise layout."""
from pathlib import Path

p = Path(r"C:\Users\prajj\Documents\proto.SIH\scripts\build_mailtrace_devwise_style.py")
text = p.read_text(encoding="utf-8")
start = text.index("def make_feasibility_diagram(")
end = text.index("def icon_person_book(")

# Use a list of lines to avoid escape hell for newlines in card labels
lines = []
a = lines.append

a("def make_feasibility_diagram(path: Path):")
a('    """DevWise feasibility triad — oversized type for slide readability."""')
a("    W, H = 1400, 480")
a('    im = Image.new("RGB", (W, H), (255, 255, 255))')
a("    d = ImageDraw.Draw(im)")
a("")
a("    # center hub")
a("    cx, cy = 700, 240")
a("    hub = (cx - 200, cy - 95, cx + 200, cy + 95)")
a("    rounded_rect(d, hub, 22, fill=(236, 236, 236), outline=(95, 100, 110), width=5)")
a("    d.ellipse((cx - 30, cy - 70, cx - 8, cy - 48), outline=(60, 65, 75), width=4)")
a("    d.ellipse((cx + 8, cy - 70, cx + 30, cy - 48), outline=(60, 65, 75), width=4)")
a("    d.arc((cx - 40, cy - 48, cx - 2, cy - 12), 200, 340, fill=(60, 65, 75), width=4)")
a("    d.arc((cx + 2, cy - 48, cx + 40, cy - 12), 200, 340, fill=(60, 65, 75), width=4)")
a('    d.text((cx, cy + 8), "Feasibility Analysis of", font=font(26), fill=(55, 60, 70), anchor="mm")')
a('    d.text((cx, cy + 48), "MailTrace Platform", font=font(32, True), fill=(25, 30, 40), anchor="mm")')
a("")
a("    def side_pill(bx, by, title, color, icon_kind):")
a("        fnt = font(30, True)")
a("        tw, th = text_size(d, title, fnt)")
a("        pad_x, pad_y, icon_w = 22, 18, 48")
a("        w = tw + icon_w + pad_x * 2 + 20")
a("        h = max(th + pad_y * 2, 70)")
a("        box = (bx - w // 2, by - h // 2, bx + w // 2, by + h // 2)")
a("        rounded_rect(d, box, 18, fill=pastel(color, 170), outline=color, width=5)")
a("        ix = bx - w // 2 + pad_x + 16")
a("        draw_mini_icon(d, icon_kind, ix, by, color)")
a('        d.text((ix + 24, by), title, font=fnt, fill=color, anchor="lm")')
a("        return box")
a("")
a("    def side_tree(pill_box, items):")
a("        x0 = pill_box[0] + 34")
a("        y0 = pill_box[3] + 10")
a("        fnt = font(26)")
a("        line_h = 40")
a("        dashed_line(d, (x0, y0), (x0, y0 + len(items) * line_h + 10), fill=(95, 100, 110), width=4, dash=7, gap=5)")
a("        for i, it in enumerate(items):")
a("            yi = y0 + 24 + i * line_h")
a("            dashed_line(d, (x0, yi), (x0 + 26, yi), fill=(95, 100, 110), width=4, dash=7, gap=5)")
a('            d.text((x0 + 34, yi), it, font=fnt, fill=(35, 40, 50), anchor="lm")')
a("")
a('    left = side_pill(220, 100, "Software & Cloud", C_GREEN, "runtime")')
a('    right = side_pill(1180, 100, "Current Technology", C_BLUE, "backend")')
a("")
a("    # straight-ish orthogonal connectors: hub side -> short stub -> up/out to pill icon side")
a("    # left: hub left-mid -> left -> up -> into right edge of left pill")
a("    lx = left[2]  # right edge of left pill")
a("    ly = (left[1] + left[3]) / 2")
a("    hx0, hy = hub[0], cy")
a("    dashed_polyline(d, [(hx0, hy), (hx0 - 40, hy), (hx0 - 40, ly), (lx, ly)], fill=(100, 105, 115), width=4, dash=9, gap=5)")
a("    # right: hub right-mid -> right -> up -> into left edge of right pill")
a("    rx = right[0]")
a("    ry = (right[1] + right[3]) / 2")
a("    hx1 = hub[2]")
a("    dashed_polyline(d, [(hx1, hy), (hx1 + 40, hy), (hx1 + 40, ry), (rx, ry)], fill=(100, 105, 115), width=4, dash=9, gap=5)")
a("")
a('    side_tree(left, ["Laptop demo ready", "No RF hardware", "No classified data"])')
a('    side_tree(right, ["Header forensics", "NLP scam cues", "Hop geolocation"])')
a("")
a("    im = _crop_white(im, pad=10)")
a("    im.save(path)")
a("    return path")
a("")
a("")
a("def make_challenges_diagram(path: Path):")
a('    """Balance-scale challenges — oversized labels."""')
a("    W, H = 1100, 400")
a('    im = Image.new("RGB", (W, H), (255, 255, 255))')
a("    d = ImageDraw.Draw(im)")
a("")
a("    mx = 550")
a("    d.line([(mx, 55), (mx, 245)], fill=(110, 115, 125), width=8)")
a("    d.line([(160, 120), (940, 120)], fill=(110, 115, 125), width=8)")
a("    d.ellipse((mx - 20, 100, mx + 20, 140), fill=(180, 185, 192), outline=(80, 85, 95), width=3)")
a("    d.polygon([(mx - 55, 245), (mx + 55, 245), (mx + 80, 310), (mx - 80, 310)],")
a("              fill=(198, 202, 208), outline=(90, 95, 105), width=3)")
a("")
a("    lx = 300")
a("    d.ellipse((lx - 90, 110, lx + 90, 175), fill=(255, 225, 205), outline=C_ORANGE, width=6)")
a("    d.line([(lx, 120), (lx, 78)], fill=C_ORANGE, width=4)")
a("    d.ellipse((lx - 26, 28, lx + 26, 80), outline=C_ORANGE, width=5)")
a("    d.ellipse((lx - 9, 45, lx + 9, 63), fill=C_ORANGE)")
a("    d.polygon([(lx, 80), (lx - 18, 115), (lx + 18, 115)], outline=C_ORANGE, width=4)")
a('    d.text((lx, 210), "Empty Geo Maps", font=font(30, True), fill=C_ORANGE, anchor="mm")')
a('    d.text((lx, 248), "(Gmail hides IP)", font=font(22), fill=(70, 75, 85), anchor="mm")')
a('    d.text((lx, 365), "Connectivity of hops", font=font(26, True), fill=(35, 40, 50), anchor="mm")')
a("")
a("    rx = 800")
a("    d.ellipse((rx - 90, 110, rx + 90, 175), fill=(234, 220, 248), outline=C_PURPLE, width=6)")
a("    d.line([(rx, 120), (rx, 78)], fill=C_PURPLE, width=4)")
a("    d.rectangle((rx - 30, 70, rx - 14, 118), fill=C_PURPLE)")
a("    d.rectangle((rx - 8, 52, rx + 8, 118), fill=C_PURPLE)")
a("    d.rectangle((rx + 14, 36, rx + 30, 118), fill=C_PURPLE)")
a('    d.text((rx, 210), "Score Noise", font=font(30, True), fill=C_PURPLE, anchor="mm")')
a('    d.text((rx, 248), "(CDN / newsletters)", font=font(22), fill=(70, 75, 85), anchor="mm")')
a('    d.text((rx, 365), "Adoption / trust risks", font=font(26, True), fill=(35, 40, 50), anchor="mm")')
a("")
a("    im = _crop_white(im, pad=8)")
a("    im.save(path)")
a("    return path")
a("")
a("")
a("def make_overcome_diagram(path: Path):")
a('    """Overcoming branch with large colorful cards."""')
a("    W, H = 980, 740")
a('    im = Image.new("RGB", (W, H), (255, 255, 255))')
a("    d = ImageDraw.Draw(im)")
a("")
a("    sx0, sy0, sx1, sy1 = 36, 270, 310, 480")
a("    rounded_rect(d, (sx0, sy0, sx1, sy1), 22, fill=(236, 236, 236), outline=(90, 95, 105), width=5)")
a("    d.polygon([(110, 315), (110, 410), (180, 362)], fill=C_CYAN)")
a("    d.line([(110, 315), (110, 440)], fill=(60, 65, 75), width=5)")
a('    d.text((215, 360), "Overcoming", font=font(28, True), fill=(30, 35, 45), anchor="mm")')
a('    d.text((215, 400), "Challenges", font=font(28, True), fill=(30, 35, 45), anchor="mm")')
a("")
a("    cards = [")
a('        (90, "Caption empty maps\\nas expected (no IPv4)", C_CYAN, "geo"),')
a('        (300, "Demo lab traces +\\nreal Show original", C_GREEN, "ingest"),')
a('        (510, "Explainable rules now;\\nML-ready features later", C_ORANGE, "analysis"),')
a("    ]")
a("")
a("    trunk_x = 360")
a("    d.line([(sx1, 375), (trunk_x, 375)], fill=(60, 65, 75), width=7)")
a("    d.line([(trunk_x, 130), (trunk_x, 620)], fill=(60, 65, 75), width=7)")
a("")
a("    for y, label, col, ikind in cards:")
a("        mid_y = y + 65")
a("        d.line([(trunk_x, mid_y), (420, mid_y)], fill=(60, 65, 75), width=7)")
a("        d.polygon([(420, mid_y), (402, mid_y - 14), (402, mid_y + 14)], fill=col)")
a("        rounded_rect(d, (430, y + 10, 940, y + 120), 20, fill=pastel(col, 165), outline=col, width=5)")
a("        d.ellipse((452, mid_y - 28, 508, mid_y + 28), fill=(255, 255, 255), outline=col, width=4)")
a("        draw_mini_icon(d, ikind, 480, mid_y, col)")
a('        d.text((700, mid_y), label, font=font(26, True), fill=col, anchor="mm", align="center")')
a("")
a("    im = _crop_white(im, pad=10)")
a("    im.save(path)")
a("    return path")
a("")
a("")

new = "\n".join(lines) + "\n"
# The cards lines currently have literal \\n (two chars) from how we wrote them in single-quoted strings.
# In lines we used: '        (90, "Caption empty maps\\nas expected (no IPv4)", C_CYAN, "geo"),'
# In Python source of THIS patch file, \\n in a single-quoted string is \n (backslash+n).
# So new already has correct \n escapes for the build file. Good.

text = text[:start] + new + text[end:]
p.write_text(text, encoding="utf-8")

# verify
src = p.read_text(encoding="utf-8")
i = src.index("Caption empty maps")
print("repr:", repr(src[i : i + 55]))
print("font(32" in src[start:start+800], "font(26)" in src[src.index("make_overcome"):src.index("make_overcome")+900])
print("ok")
