"""Compact aspect-matched feasibility diagrams so text stays large on slide."""
from pathlib import Path

p = Path(r"C:\Users\prajj\Documents\proto.SIH\scripts\build_mailtrace_devwise_style.py")
text = p.read_text(encoding="utf-8")
start = text.index("def make_feasibility_diagram(")
end = text.index("def icon_person_book(")

lines = []
a = lines.append

a("def make_feasibility_diagram(path: Path):")
a('    """Compact feasibility map matched to panel aspect (~2.8:1)."""')
a("    # Target panel ~6.35x2.25 in -> keep content filling this ratio")
a("    W, H = 980, 350")
a('    im = Image.new("RGB", (W, H), (255, 255, 255))')
a("    d = ImageDraw.Draw(im)")
a("")
a("    cx, cy = 490, 195")
a("    hub = (cx - 155, cy - 78, cx + 155, cy + 78)")
a("    rounded_rect(d, hub, 18, fill=(236, 236, 236), outline=(95, 100, 110), width=4)")
a("    d.ellipse((cx - 24, cy - 58, cx - 6, cy - 40), outline=(60, 65, 75), width=3)")
a("    d.ellipse((cx + 6, cy - 58, cx + 24, cy - 40), outline=(60, 65, 75), width=3)")
a("    d.arc((cx - 32, cy - 40, cx - 2, cy - 10), 200, 340, fill=(60, 65, 75), width=3)")
a("    d.arc((cx + 2, cy - 40, cx + 32, cy - 10), 200, 340, fill=(60, 65, 75), width=3)")
a('    d.text((cx, cy + 6), "Feasibility Analysis of", font=font(20), fill=(55, 60, 70), anchor="mm")')
a('    d.text((cx, cy + 36), "MailTrace Platform", font=font(26, True), fill=(25, 30, 40), anchor="mm")')
a("")
a("    def side_pill(bx, by, title, color, icon_kind):")
a("        fnt = font(24, True)")
a("        tw, th = text_size(d, title, fnt)")
a("        pad_x, pad_y, icon_w = 16, 12, 40")
a("        w = tw + icon_w + pad_x * 2 + 14")
a("        h = max(th + pad_y * 2, 56)")
a("        box = (bx - w // 2, by - h // 2, bx + w // 2, by + h // 2)")
a("        rounded_rect(d, box, 14, fill=pastel(color, 170), outline=color, width=4)")
a("        ix = bx - w // 2 + pad_x + 12")
a("        draw_mini_icon(d, icon_kind, ix, by, color)")
a('        d.text((ix + 20, by), title, font=fnt, fill=color, anchor="lm")')
a("        return box")
a("")
a("    def side_tree(pill_box, items):")
a("        x0 = pill_box[0] + 28")
a("        y0 = pill_box[3] + 6")
a("        fnt = font(22)")
a("        line_h = 32")
a("        dashed_line(d, (x0, y0), (x0, y0 + len(items) * line_h + 6), fill=(95, 100, 110), width=3, dash=6, gap=4)")
a("        for i, it in enumerate(items):")
a("            yi = y0 + 18 + i * line_h")
a("            dashed_line(d, (x0, yi), (x0 + 18, yi), fill=(95, 100, 110), width=3, dash=6, gap=4)")
a('            d.text((x0 + 24, yi), it, font=fnt, fill=(35, 40, 50), anchor="lm")')
a("")
a('    left = side_pill(175, 70, "Software & Cloud", C_GREEN, "runtime")')
a('    right = side_pill(805, 70, "Current Technology", C_BLUE, "backend")')
a("")
a("    # connectors hub mid-side -> pill mid-side (icon side for right/left)")
a("    ly = (left[1] + left[3]) / 2")
a("    ry = (right[1] + right[3]) / 2")
a("    dashed_polyline(d, [(hub[0], cy), (hub[0] - 28, cy), (hub[0] - 28, ly), (left[2], ly)],")
a("                    fill=(100, 105, 115), width=3, dash=8, gap=5)")
a("    dashed_polyline(d, [(hub[2], cy), (hub[2] + 28, cy), (hub[2] + 28, ry), (right[0], ry)],")
a("                    fill=(100, 105, 115), width=3, dash=8, gap=5)")
a("")
a('    side_tree(left, ["Laptop demo ready", "No RF hardware", "No classified data"])')
a('    side_tree(right, ["Header forensics", "NLP scam cues", "Hop geolocation"])')
a("")
a("    # pad to panel aspect so PPT stretch does not crush type")
a("    im = _crop_white(im, pad=8)")
a("    im = _pad_to_aspect(im, 6.35 / 2.25)")
a("    im.save(path)")
a("    return path")
a("")
a("")
a("def make_challenges_diagram(path: Path):")
a('    """Balance-scale challenges — compact, large labels."""')
a("    W, H = 900, 340")
a('    im = Image.new("RGB", (W, H), (255, 255, 255))')
a("    d = ImageDraw.Draw(im)")
a("")
a("    mx = 450")
a("    d.line([(mx, 40), (mx, 210)], fill=(110, 115, 125), width=7)")
a("    d.line([(140, 100), (760, 100)], fill=(110, 115, 125), width=7)")
a("    d.ellipse((mx - 18, 82, mx + 18, 118), fill=(180, 185, 192), outline=(80, 85, 95), width=3)")
a("    d.polygon([(mx - 48, 210), (mx + 48, 210), (mx + 70, 270), (mx - 70, 270)],")
a("              fill=(198, 202, 208), outline=(90, 95, 105), width=3)")
a("")
a("    lx = 250")
a("    d.ellipse((lx - 78, 88, lx + 78, 148), fill=(255, 225, 205), outline=C_ORANGE, width=5)")
a("    d.line([(lx, 96), (lx, 60)], fill=C_ORANGE, width=4)")
a("    d.ellipse((lx - 22, 18, lx + 22, 62), outline=C_ORANGE, width=4)")
a("    d.ellipse((lx - 8, 32, lx + 8, 48), fill=C_ORANGE)")
a("    d.polygon([(lx, 62), (lx - 14, 92), (lx + 14, 92)], outline=C_ORANGE, width=3)")
a('    d.text((lx, 178), "Empty Geo Maps", font=font(26, True), fill=C_ORANGE, anchor="mm")')
a('    d.text((lx, 208), "(Gmail hides IP)", font=font(18), fill=(70, 75, 85), anchor="mm")')
a('    d.text((lx, 310), "Connectivity of hops", font=font(22, True), fill=(35, 40, 50), anchor="mm")')
a("")
a("    rx = 650")
a("    d.ellipse((rx - 78, 88, rx + 78, 148), fill=(234, 220, 248), outline=C_PURPLE, width=5)")
a("    d.line([(rx, 96), (rx, 60)], fill=C_PURPLE, width=4)")
a("    d.rectangle((rx - 26, 55, rx - 12, 100), fill=C_PURPLE)")
a("    d.rectangle((rx - 7, 42, rx + 7, 100), fill=C_PURPLE)")
a("    d.rectangle((rx + 12, 28, rx + 26, 100), fill=C_PURPLE)")
a('    d.text((rx, 178), "Score Noise", font=font(26, True), fill=C_PURPLE, anchor="mm")')
a('    d.text((rx, 208), "(CDN / newsletters)", font=font(18), fill=(70, 75, 85), anchor="mm")')
a('    d.text((rx, 310), "Adoption / trust risks", font=font(22, True), fill=(35, 40, 50), anchor="mm")')
a("")
a("    im = _crop_white(im, pad=6)")
a("    im = _pad_to_aspect(im, 6.2 / 2.2)")
a("    im.save(path)")
a("    return path")
a("")
a("")
a("def make_overcome_diagram(path: Path):")
a('    """Overcoming branch — large teal cards like DevWise."""')
a("    W, H = 860, 680")
a('    im = Image.new("RGB", (W, H), (255, 255, 255))')
a("    d = ImageDraw.Draw(im)")
a("")
a("    sx0, sy0, sx1, sy1 = 28, 250, 270, 450")
a("    rounded_rect(d, (sx0, sy0, sx1, sy1), 20, fill=(236, 236, 236), outline=(90, 95, 105), width=4)")
a("    d.polygon([(95, 295), (95, 385), (155, 340)], fill=C_CYAN)")
a("    d.line([(95, 295), (95, 415)], fill=(60, 65, 75), width=4)")
a('    d.text((185, 335), "Overcoming", font=font(24, True), fill=(30, 35, 45), anchor="mm")')
a('    d.text((185, 370), "Challenges", font=font(24, True), fill=(30, 35, 45), anchor="mm")')
a("")
a("    cards = [")
a('        (85, "Caption empty maps\\nas expected (no IPv4)", C_CYAN, "geo"),')
a('        (280, "Demo lab traces +\\nreal Show original", C_GREEN, "ingest"),')
a('        (475, "Explainable rules now;\\nML-ready features later", C_ORANGE, "analysis"),')
a("    ]")
a("")
a("    trunk_x = 315")
a("    d.line([(sx1, 350), (trunk_x, 350)], fill=(60, 65, 75), width=6)")
a("    d.line([(trunk_x, 125), (trunk_x, 575)], fill=(60, 65, 75), width=6)")
a("")
a("    for y, label, col, ikind in cards:")
a("        mid_y = y + 60")
a("        d.line([(trunk_x, mid_y), (370, mid_y)], fill=(60, 65, 75), width=6)")
a("        d.polygon([(370, mid_y), (354, mid_y - 12), (354, mid_y + 12)], fill=col)")
a("        # DevWise-like: light blue cards with colored text")
a("        rounded_rect(d, (380, y + 8, 830, y + 112), 18, fill=(230, 242, 250), outline=C_BLUE, width=4)")
a("        d.ellipse((400, mid_y - 26, 452, mid_y + 26), fill=(255, 255, 255), outline=col, width=3)")
a("        draw_mini_icon(d, ikind, 426, mid_y, col)")
a('        d.text((620, mid_y), label, font=font(22, True), fill=C_CYAN, anchor="mm", align="center")')
a("")
a("    im = _crop_white(im, pad=8)")
a("    im = _pad_to_aspect(im, 5.8 / 5.15)")
a("    im.save(path)")
a("    return path")
a("")
a("")

new = "\n".join(lines) + "\n"
text = text[:start] + new + text[end:]

# Add _pad_to_aspect helper near _crop_white if missing
if "def _pad_to_aspect" not in text:
    helper = '''
def _pad_to_aspect(im, aspect, fill=(255, 255, 255)):
    """Pad image with white so width/height == aspect (prevents PPT squash)."""
    w, h = im.size
    cur = w / max(h, 1)
    if abs(cur - aspect) < 0.02:
        return im
    if cur > aspect:
        # too wide -> add vertical pad
        new_h = int(round(w / aspect))
        out = Image.new("RGB", (w, new_h), fill)
        out.paste(im, (0, (new_h - h) // 2))
        return out
    new_w = int(round(h * aspect))
    out = Image.new("RGB", (new_w, h), fill)
    out.paste(im, ((new_w - w) // 2, 0))
    return out


'''
    text = text.replace("def _crop_white(im, pad=18):", helper + "def _crop_white(im, pad=18):")

p.write_text(text, encoding="utf-8")
print("patched; has pad:", "def _pad_to_aspect" in p.read_text(encoding="utf-8"))
